In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)     # DataFrame용
pd.set_option('display.max_seq_items', None)  # Index/리스트류 생략 해제 (핵심)

### data

In [9]:
data_2010 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2010_교통사고정보(2010).xls')
data_2011 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2011_교통사고정보(2011).xls')
data_2012 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2012_교통사고속보자료(D급포함).xlsx')
data_2013 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2013_교통사고속보자료(D급포함).xls')
data_2014 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2014년_D급포함(20150401).xls')
data_2015 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2015년 최종.xls')
data_2016 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2016년 D급 포함.xls')
data_2017 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2017년 사고현황 최종(D급포함).xlsx')
data_2018 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2018.12.31 잠정적 집계(최종본 아님).xlsx')
data_2019 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2019_교통사고정보.xlsx')

In [10]:
data_2010.columns = data_2010.columns.str.replace('\n', '', regex=False)
data_2011.columns = data_2011.columns.str.replace('\n', '', regex=False)
data_2012.columns = data_2012.columns.str.replace('\n', '', regex=False)
data_2013.columns = data_2013.columns.str.replace('\n', '', regex=False)
data_2014.columns = data_2014.columns.str.replace('\n', '', regex=False)
data_2015.columns = data_2015.columns.str.replace('\n', '', regex=False)
data_2016.columns = data_2016.columns.str.replace('\n', '', regex=False)
data_2017.columns = data_2017.columns.str.replace('\n', '', regex=False)
data_2018.columns = data_2018.columns.str.replace('\n', '', regex=False)
data_2019.columns = data_2019.columns.str.replace('\n', '', regex=False)

In [11]:
data_2011.head()

,속보구분,지사명,사고일자,사고시간,노선명,이정,방향,발생지점,구분,차로,사고전차량통행속도,사고등급,사고원인구분,주 사고원인,사고직전차량조작,운전자상태,교통장애요인,사고시도로환경,사망,중상,경상,요일,날씨,주야구분,사고유형,갓길주정차,사고차량수,공사보유장비사고,포장구분,평면선형,선형구분,편경사,종단구배,노면상태,조명시설,포장상태,작업장구분,절성토구분,방책시설(중분대),방책시설(갓길),원인차차종,차종구분1,차종구분2,차종규격,운전시간,운전거리(km),성별,원인차운전자연령구분,피해자_차종,차종_규격,성별.1,피해차운전자연령구분,차량피해(완파),차량피해(반파),차량피해(경미),차량피해((1/3파),사망자(운전자),사망자(보행자),사망자(동승자),사망자(뒷좌석),부상자(중상),부상자(경상),사망안전벨트미착용,안전벨트착용,안전벨트미착용,안전벨트확인불가,안전벨트관계없음,사망에어백작동,사망에어백미작동,사망에어백없음,사망유아시트착용,사망유아시트미착용,사망유아시트없음,사고접보방법,현장도착소요시간,구급차도착소요시간,인명구조소요시간,견인차도착소요시간,구난소요시간,전면통제시간,부분통제시간,교통차단시간,사고처리시간,도로점유(본선차도),도로점유(중분대부근),도로점유(중분대승월),도로점유(갓길),도로점유(부가차로),도로점유도로이탈(추락),도로점유도로이탈(기타),도로점유진행방향(기타),대향차로,사고후상태(정차),사고후상태(전도),사고후상태(전복),차량상태(화재),차량상태(잭나이프),차량상태(언더라이드),사고내용,시설물피해액,피해내용,잡물종류,잡물상세,잡물보상금액,도로사정하자종류,도로사정보상금액
0,도로공사,원주지사,2011-01-01,04:35:00,영동선,117.4,강릉,본선,본선차로,1/2차로,0,D,운전자요인,졸음,운행차로주행,피로,장애없음,정상,0,1,0,토요일,맑음,야간,차-시설,관련없음,1,관련없음,콘크리트,직선,NaN,2,내리막 1% 이상 3% 미만,건조,없음,양호,비작업구간,성토고 2M 미만,고정식방호벽(81cm),가드레일,승용,소형,NaN,NaN,0,0,남자,30~40,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,고객,00:15:00,00:20:00,00:05:00,00:15:00,00:20:00,00:00:00,00:00:00,00:00:00,00:35:00,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,#차 강릉방향 주행로 주행중 졸음운전으로 차로를 이탈하여 중앙분리대 방현망을 충격하...,"527,820원",중앙분리대 방현망 1조,NaN,NaN,NaN,NaN,0
1,도로공사,대관령지사,2011-01-01,07:30:00,영동선,215,강릉,본선,본선차로,2/2차로,0,C,운전자요인,과속,운행차로주행,정상,장애없음,정상,0,1,0,토요일,눈,야간,차-시설,관련없음,1,관련없음,아스팔트,직선,NaN,NaN,오르막 1% 미만,습기,해당없음(주간),양호,비작업구간,절토부 10M 이상,기타,콘크리트방호벽,승용,소형,NaN,NaN,0,0,남자,20~30,NaN,NaN,NaN,NaN,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,고객,00:10:00,00:00:00,00:00:00,00:10:00,00:05:00,00:00:00,00:00:00,00:20:00,00:20:00,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,사고차량 인천방향 1차로 주행 중 과속으로 중분대에 설치된 비상회차로 시설물을 차량...,"3,400,000원",중분대 비상 회차로 시설물,NaN,NaN,NaN,NaN,0
2,도로공사,강릉지사,2011-01-01,06:10:00,동해선,17.8,동해,본선,본선차로,2/2차로,0,C,운전자요인,졸음,운행차로주행,정상,장애없음,정상,0,0,3,토요일,눈,야간,차-차,관련없음,2,관련없음,아스팔트,직선,NaN,NaN,평탄,적설,없음,양호,비작업구간,절토부 10M 이상,고정식방호벽(127cm),없음,승용,중형,NaN,NaN,0,0,남자,20~30,승용,NaN,여자,20~30,0,0,0,2,0,0,0,0,0,3,0,3,0,0,0,0,0,0,0,0,0,순찰중,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,1,0,0,1,0,0,0,0,0,2,0,0,0,0,0,사고#1차량 동해방향 1차로 주행중 졸음운전으로 인하여 2차로를 앞서가는 사고#2차...,NaN,없음,NaN,NaN,NaN,NaN,0
3,도로공사,천안지사,2011-01-01,06:25:00,경부선,342.5,서울,본선,본선차로,1/4차로,0,B,운전자요인,주시태만,운행차로주행,정상,본선정차차량(사고),정상,1,1,0,토요일,맑음,야간,차-사람,관련없음,3,관련없음,아스팔트,직선,NaN,NaN,내리막 1% 이상 3% 미만,건조,없음,양호,비작업구간,성토고 2M 미만,고정식방호벽(127cm),콘크리트방호벽,승용,소형,NaN,NaN,0,0,남자,30~40,승용,NaN,남자,20~30,0,0,2,1,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,콜센터,00:12:00,00:10:00,00:05:00,00:08:00,00:32:00,00:00:00,00:35:00,00:40:00,00:45:00,3,0,0,0,0,0,0,0,0,3,0,0,0,0,0,#2차(소나타)량 1차로 주행중 순간졸음으로 갓길 방음벽을 스치고 1.2차로 구분선...,NaN,없음,NaN,NaN,NaN,NaN,0
4,도로공사,고성도관,2011-01-01,14:47:00,"중부선,통영-대전선",12.5,통영,본선,본선차로,2/2차로,0,C,운전자요인,안전거리미확보,운행차로주행,정상,장애없음,정상,0,1,0,토요일,맑음,주간,차-차,관련없음,2,관련없음,콘크리트,우커브 1000m 이상,NaN,NaN,내리막 1% 이상 3% 미만,건조,해당없음(주간),양호,비작업구간,성토고 2M 미만,녹지대,기타,승용,소형,NaN,NaN,0,0,남자,40~50,트레일러,1톤,남자,NaN,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,고객,00:05:00,00:09:00,00:17:00,00:00:00,00:26:00,00:00:00,00:26:00,00:00:00,00:26:00,2,0,0,0,0,0,0,0,0,2,0,0,0,0,0,#2차(현대포터) 통영방향 #2차로 운행중 전방 차량 서행으로 제동을 가한것이 미끄...,NaN,없음,NaN,NaN,NaN,NaN,0

-----

In [12]:
data_2010.columns

Index(['지사명', '년도', '사고일자', '사고시간', '노선명', '이정', '방향', '최초사고지점_도로시설', '지점명',
       '사고등급', '사고원인구분', '사고원인', '건수', '사망', '부상', '요일', '날씨', '주야구분', '사고유형',
       '갓길주정차', '사고차량수', '포장구분', '평면선형', '종단구배', '노면상태', '조명시설', '포장상태',
       '작업장구분', '절성토구분', '방책시설_중분대', '방책시설_갓길', '원인차_차종', '차종_규격', '성별',
       '원인차운전자연령구분', '피해자_차종', '차종_규격.1', '성별.1', '피해차운전자연령구분', '차량피해구분_완파',
       '차량피해구분_반파', '차량피해구분_경미', '차량피해구분_3분의1파', '사망자구분_운전자', '사망자구분_탑승자',
       '사망자구분_보행자', '사망자구분_운전석', '사망자구분_조수석', '사망자구분_뒷좌석', '부상자', '사망안전벨트미착용',
       '안전벨트착용', '안전벨트미착용', '안전벨트확인불가', '안전벨트관계없음', '사고접보방법', '현장도착소요시간',
       '구급차도착소요시간', '인명구조소요시간', '견인차도착소요시간', '구난소요시간', '전면통제시간', '부분통제시간',
       '교통차단시간', '사고처리시간', '도로점유상태_진행방향_본선', '도로점유상태_진행방향_중분대',
       '도로점유상태_진행방향_갓길', '도로점유상태_진행방향_도로외', '도로점유상태_진행방향_기타', '도로점유상태_반대방향_본선',
       '도로점유상태_반대방향_중분대', '도로점유상태_반대방향_갓길', '도로점유상태_반대방향_도로외',
       '도로점유상태_반대방향_기타', '사고후상태_정차', '사고후상태_전도', '사고후상태_전복', '사고후상태_추락',
       '사고후상태_화재', '사고후상태_기타', '@사고내용', '시설물피해액', '@피해내용', '잡물종류', '잡물상세',
       '잡물보상금액', '도로사정하자종류', '도로사정보상금액'],
      dtype='object')

In [13]:
# 2011 데이터의 컬럼 이름과 2013 데이터의 컬럼 이름 비교
cols_2010 = data_2010.columns
cols_2013 = data_2013.columns


only_in_df2011 = cols_2010.difference(cols_2013)

only_in_df2013 = cols_2013.difference(cols_2010)

print("\n2010에만 있는 컬럼")
print(*only_in_df2011, sep="\n")

print("\n2013에만 있는 컬럼")
print(*only_in_df2013, sep="\n")

2010에만 있는 컬럼
@사고내용
@피해내용
갓길주정차
년도
도로사정보상금액
도로사정하자종류
도로점유상태_반대방향_갓길
도로점유상태_반대방향_기타
도로점유상태_반대방향_도로외
도로점유상태_반대방향_본선
도로점유상태_반대방향_중분대
도로점유상태_진행방향_갓길
도로점유상태_진행방향_기타
도로점유상태_진행방향_도로외
도로점유상태_진행방향_본선
도로점유상태_진행방향_중분대
방책시설_갓길
방책시설_중분대
부상자
사고원인
사고후상태_기타
사고후상태_전도
사고후상태_전복
사고후상태_정차
사고후상태_추락
사고후상태_화재
사망자구분_뒷좌석
사망자구분_보행자
사망자구분_운전석
사망자구분_운전자
사망자구분_조수석
사망자구분_탑승자
원인차_차종
잡물보상금액
잡물상세
잡물종류
종단구배
지점명
차량피해구분_3분의1파
차량피해구분_경미
차량피해구분_반파
차량피해구분_완파
차종_규격.1
최초사고지점_도로시설

2013에만 있는 컬럼
경상
공사보유장비사고
교통장애요인
구분
대향차로
도로점유(갓길)
도로점유(본선차도)
도로점유(부가차로)
도로점유(중분대부근)
도로점유(중분대승월)
도로점유도로이탈(기타)
도로점유도로이탈(추락)
도로점유진행방향(기타)
발생지점
방책시설(갓길)
방책시설(중분대)
부상자(경상)
부상자(중상)
사고내용
사고시도로환경
사고유형(2차)
사고전차량통행속도
사고직전차량조작
사고후상태(전도)
사고후상태(전복)
사고후상태(정차)
사망에어백미작동
사망에어백없음
사망에어백작동
사망유아시트미착용
사망유아시트없음
사망유아시트착용
사망자(뒷좌석)
사망자(보행자)
사망자(운전자)
사망자(조수석)
선형구분
속보구분
운전거리(km)
운전시간
운전자상태
원인차차종
접보도착시간
종단경사
주 사고원인
중상
차량상태(언더라이드)
차량상태(잭나이프)
차량상태(화재)
차량피해((1/3파)
차량피해(경미)
차량피해(반파)
차량피해(완파)
차로
차종구분1
차종구분2
차종규격
편경사
피해내용

### 2011~2014 데이터 확인

In [14]:
data_2011.shape , data_2012.shape , data_2013.shape , data_2014.shape

((9813, 106), (10358, 109), (9703, 104), (9900, 109))

In [15]:
data_2011.columns

Index(['속보구분', '지사명', '사고일자', '사고시간', '노선명', '이정', '방향', '발생지점', '구분', '차로',
       '사고전차량통행속도', '사고등급', '사고원인구분', '주 사고원인', '사고직전차량조작', '운전자상태', '교통장애요인',
       '사고시도로환경', '사망', '중상', '경상', '요일', '날씨', '주야구분', '사고유형', '갓길주정차',
       '사고차량수', '공사보유장비사고', '포장구분', '평면선형', '선형구분', '편경사', '종단구배', '노면상태',
       '조명시설', '포장상태', '작업장구분', '절성토구분', '방책시설(중분대)', '방책시설(갓길)', '원인차차종',
       '차종구분1', '차종구분2', '차종규격', '운전시간', '운전거리(km)', '성별', '원인차운전자연령구분',
       '피해자_차종', '차종_규격', '성별.1', '피해차운전자연령구분', '차량피해(완파)', '차량피해(반파)',
       '차량피해(경미)', '차량피해((1/3파)', '사망자(운전자)', '사망자(보행자)', '사망자(동승자)',
       '사망자(뒷좌석)', '부상자(중상)', '부상자(경상)', '사망안전벨트미착용', '안전벨트착용', '안전벨트미착용',
       '안전벨트확인불가', '안전벨트관계없음', '사망에어백작동', '사망에어백미작동', '사망에어백없음', '사망유아시트착용',
       '사망유아시트미착용', '사망유아시트없음', '사고접보방법', '현장도착소요시간', '구급차도착소요시간', '인명구조소요시간',
       '견인차도착소요시간', '구난소요시간', '전면통제시간', '부분통제시간', '교통차단시간', '사고처리시간',
       '도로점유(본선차도)', '도로점유(중분대부근)', '도로점유(중분대승월)', '도로점유(갓길)', '도로점유(부가차로)',
       '도로점유도로이탈(추락)', '도로점유도로이탈(기타)', '도로점유진행방향(기타)', '대향차로', '사고후상태(정차)',
       '사고후상태(전도)', '사고후상태(전복)', '차량상태(화재)', '차량상태(잭나이프)', '차량상태(언더라이드)',
       '사고내용', '시설물피해액', '피해내용', '잡물종류', '잡물상세', '잡물보상금액', '도로사정하자종류',
       '도로사정보상금액'],
      dtype='object')

In [16]:
data_2013.columns

Index(['속보구분', '지사명', '사고일자', '사고시간', '노선명', '이정', '방향', '건수', '사망', '부상',
       '중상', '경상', '발생지점', '구분', '차로', '사고전차량통행속도', '사고등급', '사고원인구분', '주 사고원인',
       '사고직전차량조작', '운전자상태', '교통장애요인', '사고시도로환경', '요일', '날씨', '주야구분', '사고유형',
       '사고유형(2차)', '사고차량수', '공사보유장비사고', '포장구분', '평면선형', '선형구분', '편경사', '종단경사',
       '노면상태', '조명시설', '포장상태', '작업장구분', '절성토구분', '방책시설(중분대)', '방책시설(갓길)',
       '원인차차종', '차종구분1', '차종구분2', '차종규격', '운전시간', '운전거리(km)', '성별',
       '원인차운전자연령구분', '피해자_차종', '차종_규격', '성별.1', '피해차운전자연령구분', '차량피해(완파)',
       '차량피해(반파)', '차량피해(경미)', '차량피해((1/3파)', '사망자(운전자)', '사망자(보행자)',
       '사망자(조수석)', '사망자(뒷좌석)', '부상자(중상)', '부상자(경상)', '사망안전벨트미착용', '안전벨트착용',
       '안전벨트미착용', '안전벨트확인불가', '안전벨트관계없음', '사망에어백작동', '사망에어백미작동', '사망에어백없음',
       '사망유아시트착용', '사망유아시트미착용', '사망유아시트없음', '사고접보방법', '접보도착시간', '현장도착소요시간',
       '구급차도착소요시간', '인명구조소요시간', '견인차도착소요시간', '구난소요시간', '전면통제시간', '부분통제시간',
       '교통차단시간', '사고처리시간', '도로점유(본선차도)', '도로점유(중분대부근)', '도로점유(중분대승월)',
       '도로점유(갓길)', '도로점유(부가차로)', '도로점유도로이탈(추락)', '도로점유도로이탈(기타)',
       '도로점유진행방향(기타)', '대향차로', '사고후상태(정차)', '사고후상태(전도)', '사고후상태(전복)',
       '차량상태(화재)', '차량상태(잭나이프)', '차량상태(언더라이드)', '사고내용', '시설물피해액', '피해내용'],
      dtype='object')

In [17]:
data_2014.columns

Index(['지사명', '사고일자', '사고시간', '노선명', '이정', '방향', '건수', '사망', '부상', '중상', '경상',
       '발생지점', '발생지점명', '구분', '차로', '사고전차량통행속도', '사고등급', '사고원인구분', '주 사고원인',
       '사고직전차량조작', '운전자상태', '교통장애요인', '사고시도로환경', '요일', '날씨', '주야구분', '사고유형',
       '사고유형(2차)', '사고차량수', '공사보유장비사고', '포장구분', '평면선형', '선형구분', '편경사', '종단경사',
       '노면상태', '조명시설', '포장상태', '작업장구분', '절성토구분', '방책시설(중분대)', '방책시설(갓길)',
       '원인차차량번호', '원인차차종', '차종구분1', '차종구분2', '차종규격', '운전시간', '운전거리(km)', '성별',
       '원인차운전자연령구분', '피해자_차종', '차종_규격', '성별.1', '피해차운전자연령구분', '차량피해(완파)',
       '차량피해(반파)', '차량피해(경미)', '차량피해((1/3파)', '사망자(운전자)', '사망자(보행자)',
       '사망자(조수석)', '사망자(뒷좌석)', '사망안전벨트미착용(운전자)', '사망안전벨트미착용(조수석)',
       '사망안전벨트미착용(뒷좌석)', '사망안전벨트착용(운전자)', '사망안전벨트착용(조수석)', '사망안전벨트착용(뒷좌석)',
       '사망안전벨트확인불가(운전자)', '사망안전벨트확인불가(조수석)', '사망안전벨트확인불가(뒷좌석)', '사망안전벨트관계없음',
       '사망에어백작동', '사망에어백미작동', '사망에어백없음', '사망유아시트착용', '사망유아시트미착용', '사망유아시트없음',
       '사고접보방법', '접보도착시간', '현장도착소요시간', '구급차도착소요시간', '인명구조소요시간', '견인차도착소요시간',
       '구난소요시간', '전면통제시간', '부분통제시간', '교통차단시간', '사고처리시간', '도로점유(본선차도)',
       '도로점유(중분대부근)', '도로점유(중분대승월)', '도로점유(갓길)', '도로점유(부가차로)', '도로점유도로이탈(추락)',
       '도로점유도로이탈(기타)', '도로점유진행방향(기타)', '대향차로', '사고후상태(정차)', '사고후상태(전도)',
       '사고후상태(전복)', '차량상태(화재)', '차량상태(잭나이프)', '차량상태(언더라이드)', '사고내용', '시설물피해액',
       '피해내용', '행정구역'],
      dtype='object')

In [18]:
cols = [
    '사망안전벨트미착용(뒷좌석)',
    '사망안전벨트미착용(운전자)',
    '사망안전벨트미착용(조수석)'
]

# 혹시 문자형이 섞여 있을 경우를 대비
data_2014[cols] = data_2014[cols].apply(pd.to_numeric, errors='coerce').fillna(0)

# 합산 컬럼 생성
data_2014['사망안전벨트미착용'] = data_2014[cols].sum(axis=1)

# 기존 세부 컬럼 삭제
data_2014 = data_2014.drop(columns=cols)

In [19]:
cols_2011 = set(data_2011.columns)
cols_2012 = set(data_2012.columns)
cols_2013 = set(data_2013.columns)
cols_2014 = set(data_2014.columns)

In [20]:
common_cols = cols_2011 & cols_2012 & cols_2013 & cols_2014
len(common_cols)

91

In [21]:
diff_2011 = cols_2011 - common_cols
diff_2012 = cols_2012 - common_cols
diff_2013 = cols_2013 - common_cols
diff_2014 = cols_2014 - common_cols

In [22]:
print("2011에만 있거나 공통이 아닌 컬럼:", sorted(diff_2011))
print("2012에만 있거나 공통이 아닌 컬럼:", sorted(diff_2012))
print("2013에만 있거나 공통이 아닌 컬럼:", sorted(diff_2013))
print("2014에만 있거나 공통이 아닌 컬럼:", sorted(diff_2014))

2011에만 있거나 공통이 아닌 컬럼: ['갓길주정차', '도로사정보상금액', '도로사정하자종류', '부상자(경상)', '부상자(중상)', '사망자(동승자)', '속보구분', '안전벨트관계없음', '안전벨트미착용', '안전벨트착용', '안전벨트확인불가', '잡물보상금액', '잡물상세', '잡물종류', '종단구배']
2012에만 있거나 공통이 아닌 컬럼: ['Unnamed: 11', '갓길주정차', '건수', '도로사정보상금액', '도로사정하자종류', '부상자(경상)', '부상자(중상)', '사망자(동승자)', '속보구분', '안전벨트관계없음', '안전벨트미착용', '안전벨트착용', '안전벨트확인불가', '잡물보상금액', '잡물상세', '잡물종류', '접보도착시간', '종단구배']
2013에만 있거나 공통이 아닌 컬럼: ['건수', '부상', '부상자(경상)', '부상자(중상)', '사고유형(2차)', '사망자(조수석)', '속보구분', '안전벨트관계없음', '안전벨트미착용', '안전벨트착용', '안전벨트확인불가', '접보도착시간', '종단경사']
2014에만 있거나 공통이 아닌 컬럼: ['건수', '발생지점명', '부상', '사고유형(2차)', '사망안전벨트관계없음', '사망안전벨트착용(뒷좌석)', '사망안전벨트착용(운전자)', '사망안전벨트착용(조수석)', '사망안전벨트확인불가(뒷좌석)', '사망안전벨트확인불가(운전자)', '사망안전벨트확인불가(조수석)', '사망자(조수석)', '원인차차량번호', '접보도착시간', '종단경사', '행정구역']

In [23]:
pd.DataFrame({
    '2011': [len(cols_2011)],
    '2012': [len(cols_2012)],
    '2013': [len(cols_2013)],
    '2014': [len(cols_2014)],
    '공통컬럼수': [len(common_cols)]
})

   2011  2012  2013  2014  공통컬럼수
0   106   109   104   107     91

In [24]:
### 2011 ~ 2014까지 최종적으로 사용할 컬럼명
common_cols

{'견인차도착소요시간',
 '경상',
 '공사보유장비사고',
 '교통장애요인',
 '교통차단시간',
 '구급차도착소요시간',
 '구난소요시간',
 '구분',
 '날씨',
 '노면상태',
 '노선명',
 '대향차로',
 '도로점유(갓길)',
 '도로점유(본선차도)',
 '도로점유(부가차로)',
 '도로점유(중분대부근)',
 '도로점유(중분대승월)',
 '도로점유도로이탈(기타)',
 '도로점유도로이탈(추락)',
 '도로점유진행방향(기타)',
 '발생지점',
 '방책시설(갓길)',
 '방책시설(중분대)',
 '방향',
 '부분통제시간',
 '사고내용',
 '사고등급',
 '사고시간',
 '사고시도로환경',
 '사고원인구분',
 '사고유형',
 '사고일자',
 '사고전차량통행속도',
 '사고접보방법',
 '사고직전차량조작',
 '사고차량수',
 '사고처리시간',
 '사고후상태(전도)',
 '사고후상태(전복)',
 '사고후상태(정차)',
 '사망',
 '사망안전벨트미착용',
 '사망에어백미작동',
 '사망에어백없음',
 '사망에어백작동',
 '사망유아시트미착용',
 '사망유아시트없음',
 '사망유아시트착용',
 '사망자(뒷좌석)',
 '사망자(보행자)',
 '사망자(운전자)',
 '선형구분',
 '성별',
 '성별.1',
 '시설물피해액',
 '요일',
 '운전거리(km)',
 '운전시간',
 '운전자상태',
 '원인차운전자연령구분',
 '원인차차종',
 '이정',
 '인명구조소요시간',
 '작업장구분',
 '전면통제시간',
 '절성토구분',
 '조명시설',
 '주 사고원인',
 '주야구분',
 '중상',
 '지사명',
 '차량상태(언더라이드)',
 '차량상태(잭나이프)',
 '차량상태(화재)',
 '차량피해((1/3파)',
 '차량피해(경미)',
 '차량피해(반파)',
 '차량피해(완파)',
 '차로',
 '차종_규격',
 '차종구분1',
 '차종구분2',
 '차종규격',
 '편경사',
 '평면선형',
 '포장구분',
 '포장상태',
 '피해내용',
 '피해자_차종',
 '피해차운전자연령구분',
 '현장도착소요시간'}

In [25]:
pd.reset_option('display.max_columns')

In [26]:
data_2011.head()

,속보구분,지사명,사고일자,사고시간,노선명,이정,방향,발생지점,구분,차로,...,차량상태(잭나이프),차량상태(언더라이드),사고내용,시설물피해액,피해내용,잡물종류,잡물상세,잡물보상금액,도로사정하자종류,도로사정보상금액
0,도로공사,원주지사,2011-01-01,04:35:00,영동선,117.4,강릉,본선,본선차로,1/2차로,...,0,0,#차 강릉방향 주행로 주행중 졸음운전으로 차로를 이탈하여 중앙분리대 방현망을 충격하...,"527,820원",중앙분리대 방현망 1조,NaN,NaN,NaN,NaN,0
1,도로공사,대관령지사,2011-01-01,07:30:00,영동선,215,강릉,본선,본선차로,2/2차로,...,0,0,사고차량 인천방향 1차로 주행 중 과속으로 중분대에 설치된 비상회차로 시설물을 차량...,"3,400,000원",중분대 비상 회차로 시설물,NaN,NaN,NaN,NaN,0
2,도로공사,강릉지사,2011-01-01,06:10:00,동해선,17.8,동해,본선,본선차로,2/2차로,...,0,0,사고#1차량 동해방향 1차로 주행중 졸음운전으로 인하여 2차로를 앞서가는 사고#2차...,NaN,없음,NaN,NaN,NaN,NaN,0
3,도로공사,천안지사,2011-01-01,06:25:00,경부선,342.5,서울,본선,본선차로,1/4차로,...,0,0,#2차(소나타)량 1차로 주행중 순간졸음으로 갓길 방음벽을 스치고 1.2차로 구분선...,NaN,없음,NaN,NaN,NaN,NaN,0
4,도로공사,고성도관,2011-01-01,14:47:00,"중부선,통영-대전선",12.5,통영,본선,본선차로,2/2차로,...,0,0,#2차(현대포터) 통영방향 #2차로 운행중 전방 차량 서행으로 제동을 가한것이 미끄...,NaN,없음,NaN,NaN,NaN,NaN,0

In [27]:
### 2011 ~ 2014 데이터 같은 열끼리 결합
df_all = pd.concat(
    [data_2011, data_2012, data_2013, data_2014],
    axis=0,
    join='inner',      # 공통 열만 사용
    ignore_index=True  # 인덱스 재정렬
)

In [28]:
df_all

,지사명,사고일자,사고시간,노선명,이정,방향,발생지점,구분,차로,사고전차량통행속도,...,대향차로,사고후상태(정차),사고후상태(전도),사고후상태(전복),차량상태(화재),차량상태(잭나이프),차량상태(언더라이드),사고내용,시설물피해액,피해내용
0,원주지사,2011-01-01 00:00:00,04:35:00,영동선,117.4,강릉,본선,본선차로,1/2차로,0,...,0,1,0,0,0,0,0,#차 강릉방향 주행로 주행중 졸음운전으로 차로를 이탈하여 중앙분리대 방현망을 충격하...,"527,820원",중앙분리대 방현망 1조
1,대관령지사,2011-01-01 00:00:00,07:30:00,영동선,215,강릉,본선,본선차로,2/2차로,0,...,0,1,0,0,0,0,0,사고차량 인천방향 1차로 주행 중 과속으로 중분대에 설치된 비상회차로 시설물을 차량...,"3,400,000원",중분대 비상 회차로 시설물
2,강릉지사,2011-01-01 00:00:00,06:10:00,동해선,17.8,동해,본선,본선차로,2/2차로,0,...,0,2,0,0,0,0,0,사고#1차량 동해방향 1차로 주행중 졸음운전으로 인하여 2차로를 앞서가는 사고#2차...,NaN,없음
3,천안지사,2011-01-01 00:00:00,06:25:00,경부선,342.5,서울,본선,본선차로,1/4차로,0,...,0,3,0,0,0,0,0,#2차(소나타)량 1차로 주행중 순간졸음으로 갓길 방음벽을 스치고 1.2차로 구분선...,NaN,없음
4,고성도관,2011-01-01 00:00:00,14:47:00,"중부선,통영-대전선",12.5,통영,본선,본선차로,2/2차로,0,...,0,2,0,0,0,0,0,#2차(현대포터) 통영방향 #2차로 운행중 전방 차량 서행으로 제동을 가한것이 미끄...,NaN,없음
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39769,진주지사,2014-12-31 00:00:00,18:50:00,남해선(순천부산),72.5,부산,본선,본선차로,3/4차로,67,...,0,1,0,0,0,0,0,*사고차량(코란도스포츠) 부산방향 3차로 운행중 핸들과대조작으로 갓길에 설치된 가드...,"3,658,960원",가드파이프9매 지주3본
39770,고령지사,2014-12-31 00:00:00,18:50:00,88올림픽선,124.7,대구,본선,갓길,NaN,80,...,0,0,0,1,0,0,0,#1 사고차량 광주-대구 운행중 급격한 핸들조작(주시태만)으로 인해 차량 중심을 잃...,NaN,PE드럼 3개
39771,창원지사,2014-12-31 00:00:00,20:19:00,남해선(순천부산),116.3,부산,램프,차로,클로버형,96,...,0,1,0,0,0,0,0,#1차(승용) 부산방향 2차로 4차로 편도2) 주행중 칠원램프로 진입코자 핸들을 조...,NaN,없슴
39772,진천지사,2014-12-31 00:00:00,22:20:00,"중부선,통영대전선",253.4,통영,램프,차로,다이아몬드형,0,...,0,1,0,0,0,0,0,사고차량 통영방향 서청주I/C 진출램프 1차로 주행중 과속으로 진행중심을 잃고 차량...,"468,590원","가드레일1매,지주1본"
39773,함평지사,2014-12-31 00:00:00,23:35:00,서해안선,22.9,서울,본선,본선차로,1/1차로,90,...,0,1,0,0,0,0,0,사고차량(코란도) 서울방향 2차로 주행중 눈길 과속으로 중분대 가드레일을 충격하고 ...,"2,000,000원",1.가드레일 1장. 지주 1본\n2.배수로 다이크 1M X 50cm

-----

### 2015 ~ 2019

In [29]:
data_2015_2019 = pd.read_excel(r'D:\LAB\world ITS\속보자료\2015-2019_교통사고정보_취합분석.xlsx')
data_2015_2019.shape

(43523, 114)

In [30]:
data_2015_2019.columns = data_2015_2019.columns.str.replace('\n', '', regex=False)

In [31]:
data_2015_2019.columns

Index(['본부명', '지사명', '사고일자', '월별구분', '사고시간', '시간단위(1시간)', '시간단위(3시간)', '주야구분',
       '노선명', '이정', '방향', '건수', '사망', '부상', '중상', '경상', '발생지점', '발생지점명', '구분',
       '차로', '사고전차량통행속도', '사고등급', '사고원인구분', '주 사고원인', '사고직전차량조작', '운전자상태',
       '교통장애요인', '사고시도로환경', '요일', '날씨', '주야구분.1', '사고유형', '사고유형(2차)', '사고차량수',
       '공사보유장비사고', '포장구분', '평면선형', '선형구분', '편경사', '종단경사', '노면상태', '조명시설',
       '포장상태', '작업장구분', '절성토구분', '방책시설(중분대)', '방책시설(갓길)', '원인차차량번호', '원인차차종',
       '차종구분1', '차종구분2', '차종규격', '운전시간', '운전거리(km)', '성별', '원인차운전자연령',
       '피해자_차종', '차종_규격', '성별.1', '피해차운전자연령', '차량피해(완파)', '차량피해(반파)',
       '차량피해(경미)', '차량피해((1/3파)', '사망자(운전자)', '사망자(보행자)', '사망자(조수석)',
       '사망자(뒷좌석)', '사망안전벨트미착용(운전자)', '사망안전벨트미착용(조수석)', '사망안전벨트미착용(뒷좌석)',
       '사망안전벨트착용(운전자)', '사망안전벨트착용(조수석)', '사망안전벨트착용(뒷좌석)', '사망안전벨트확인불가(운전자)',
       '사망안전벨트확인불가(조수석)', '사망안전벨트확인불가(뒷좌석)', '사망안전벨트관계없음', '사망에어백작동',
       '사망에어백미작동', '사망에어백없음', '사망유아시트착용', '사망유아시트미착용', '사망유아시트없음', '사고접보방법',
       '접보도착시간', '현장도착소요시간', '구급차도착소요시간', '인명구조소요시간', '견인차도착소요시간', '구난소요시간',
       '전면통제시간', '부분통제시간', '교통차단시간', '사고처리시간', '도로점유(본선차도)', '도로점유(중분대부근)',
       '도로점유(중분대승월)', '도로점유(갓길)', '도로점유(부가차로)', '도로점유도로이탈(추락)', '도로점유도로이탈(기타)',
       '도로점유진행방향(기타)', '대향차로', '사고후상태(정차)', '사고후상태(전도)', '사고후상태(전복)',
       '차량상태(화재)', '차량상태(잭나이프)', '차량상태(언더라이드)', '사고내용', '시설물피해액', '피해내용',
       '행정구역'],
      dtype='object')

In [ ]:
cols_not = [
    '사망안전벨트미착용(뒷좌석)',
    '사망안전벨트미착용(운전자)',
    '사망안전벨트미착용(조수석)'
]

cols_yes = [
    '사망안전벨트착용(뒷좌석)',
    '사망안전벨트착용(운전자)',
    '사망안전벨트착용(조수석)'
]

cols_unknown = [
    '사망안전벨트확인불가(뒷좌석)',
    '사망안전벨트확인불가(운전자)',
    '사망안전벨트확인불가(조수석)'
]

all_cols = cols_not + cols_yes + cols_unknown
data_2015_2019[all_cols] = (
    data_2015_2019[all_cols]
    .apply(pd.to_numeric, errors='coerce')
    .fillna(0)
)

data_2015_2019['사망안전벨트미착용'] = data_2015_2019[cols_not].sum(axis=1)
data_2015_2019['사망안전벨트착용']   = data_2015_2019[cols_yes].sum(axis=1)
data_2015_2019['사망안전벨트확인불가'] = data_2015_2019[cols_unknown].sum(axis=1)

data_2015_2019 = data_2015_2019.drop(columns=all_cols)

In [39]:
### 원인차운전자연령 -> 원인차운전자연령구분 / 피해차운전자연령 -> 피해차운전자연령구분 으로 각각 열 이름 변경
data_2015_2019 = data_2015_2019.rename(columns={
    '원인차운전자연령': '원인차운전자연령구분',
    '피해차운전자연령': '피해차운전자연령구분'
})

In [40]:
# 2011 데이터의 컬럼 이름과 2013 데이터의 컬럼 이름 비교
cols_df_all = df_all.columns
cols_2015_2019 = data_2015_2019.columns


only_in_df2011 = cols_df_all.difference(cols_2015_2019)

only_in_df2012 = cols_2015_2019.difference(cols_df_all)

print("\ndf_all에만 있는 컬럼")
print(*only_in_df2011, sep="\n")

print("\n2015~2019에만 있는 컬럼")
print(*only_in_df2012, sep="\n")

df_all에만 있는 컬럼


2015~2019에만 있는 컬럼
건수
발생지점명
본부명
부상
사고유형(2차)
사망안전벨트관계없음
사망안전벨트착용
사망안전벨트확인불가
사망자(조수석)
시간단위(1시간)
시간단위(3시간)
원인차차량번호
월별구분
접보도착시간
종단경사
주야구분.1
행정구역

In [41]:
### df_all(2011~2014) + data_2015_2019 = df_total
df_total = pd.concat(
    [df_all, data_2015_2019],
    axis=0,
    join='inner',      # 공통 컬럼만 유지
    ignore_index=True  # 인덱스 재정렬
)

In [44]:
df_total.head()

,지사명,사고일자,사고시간,노선명,이정,방향,발생지점,구분,차로,사고전차량통행속도,...,대향차로,사고후상태(정차),사고후상태(전도),사고후상태(전복),차량상태(화재),차량상태(잭나이프),차량상태(언더라이드),사고내용,시설물피해액,피해내용
0,원주지사,2011-01-01 00:00:00,04:35:00,영동선,117.4,강릉,본선,본선차로,1/2차로,0.0,...,0,1,0,0,0,0,0,#차 강릉방향 주행로 주행중 졸음운전으로 차로를 이탈하여 중앙분리대 방현망을 충격하...,"527,820원",중앙분리대 방현망 1조
1,대관령지사,2011-01-01 00:00:00,07:30:00,영동선,215,강릉,본선,본선차로,2/2차로,0.0,...,0,1,0,0,0,0,0,사고차량 인천방향 1차로 주행 중 과속으로 중분대에 설치된 비상회차로 시설물을 차량...,"3,400,000원",중분대 비상 회차로 시설물
2,강릉지사,2011-01-01 00:00:00,06:10:00,동해선,17.8,동해,본선,본선차로,2/2차로,0.0,...,0,2,0,0,0,0,0,사고#1차량 동해방향 1차로 주행중 졸음운전으로 인하여 2차로를 앞서가는 사고#2차...,NaN,없음
3,천안지사,2011-01-01 00:00:00,06:25:00,경부선,342.5,서울,본선,본선차로,1/4차로,0.0,...,0,3,0,0,0,0,0,#2차(소나타)량 1차로 주행중 순간졸음으로 갓길 방음벽을 스치고 1.2차로 구분선...,NaN,없음
4,고성도관,2011-01-01 00:00:00,14:47:00,"중부선,통영-대전선",12.5,통영,본선,본선차로,2/2차로,0.0,...,0,2,0,0,0,0,0,#2차(현대포터) 통영방향 #2차로 운행중 전방 차량 서행으로 제동을 가한것이 미끄...,NaN,없음

In [46]:
df_total.shape

(83297, 91)

### df_total 데이터 저장

In [ ]:
# df_total.to_csv(
#     '2011~2019 교통사고 통합 데이터.csv',
#     index=False,
#     encoding='utf-8-sig'
# )

In [45]:
df_total.columns

Index(['지사명', '사고일자', '사고시간', '노선명', '이정', '방향', '발생지점', '구분', '차로',
       '사고전차량통행속도', '사고등급', '사고원인구분', '주 사고원인', '사고직전차량조작', '운전자상태', '교통장애요인',
       '사고시도로환경', '사망', '중상', '경상', '요일', '날씨', '주야구분', '사고유형', '사고차량수',
       '공사보유장비사고', '포장구분', '평면선형', '선형구분', '편경사', '노면상태', '조명시설', '포장상태',
       '작업장구분', '절성토구분', '방책시설(중분대)', '방책시설(갓길)', '원인차차종', '차종구분1', '차종구분2',
       '차종규격', '운전시간', '운전거리(km)', '성별', '원인차운전자연령구분', '피해자_차종', '차종_규격',
       '성별.1', '피해차운전자연령구분', '차량피해(완파)', '차량피해(반파)', '차량피해(경미)', '차량피해((1/3파)',
       '사망자(운전자)', '사망자(보행자)', '사망자(뒷좌석)', '사망안전벨트미착용', '사망에어백작동', '사망에어백미작동',
       '사망에어백없음', '사망유아시트착용', '사망유아시트미착용', '사망유아시트없음', '사고접보방법', '현장도착소요시간',
       '구급차도착소요시간', '인명구조소요시간', '견인차도착소요시간', '구난소요시간', '전면통제시간', '부분통제시간',
       '교통차단시간', '사고처리시간', '도로점유(본선차도)', '도로점유(중분대부근)', '도로점유(중분대승월)',
       '도로점유(갓길)', '도로점유(부가차로)', '도로점유도로이탈(추락)', '도로점유도로이탈(기타)',
       '도로점유진행방향(기타)', '대향차로', '사고후상태(정차)', '사고후상태(전도)', '사고후상태(전복)',
       '차량상태(화재)', '차량상태(잭나이프)', '차량상태(언더라이드)', '사고내용', '시설물피해액', '피해내용'],
      dtype='object')

-----

### 전체 데이터 분석

In [3]:
import pandas as pd
import numpy as np

In [3]:
pd.reset_option('display.max_columns')

In [4]:
file = pd.read_csv(r'C:\Users\user\Documents\LAB\data\속보자료\2011~2019 교통사고 통합 데이터.csv')

C:\Users\user\AppData\Local\Temp\ipykernel_16960\3665988348.py:1: DtypeWarning: Columns (0: 사고일자, 1: 이정, 2: 편경사, 3: 포장상태, 4: 원인차운전자연령구분, 5: 차종_규격, 6: 성별.1, 7: 피해차운전자연령구분) have mixed types. Specify dtype option on import or set low_memory=False.
  file = pd.read_csv(r'C:\Users\user\Documents\LAB\data\속보자료\2011~2019 교통사고 통합 데이터.csv')

In [5]:
file.head()

,지사명,사고일자,사고시간,노선명,이정,방향,발생지점,구분,차로,사고전차량통행속도,...,대향차로,사고후상태(정차),사고후상태(전도),사고후상태(전복),차량상태(화재),차량상태(잭나이프),차량상태(언더라이드),사고내용,시설물피해액,피해내용
0,원주지사,2011-01-01 00:00:00,04:35:00,영동선,117.4,강릉,본선,본선차로,1/2차로,0.0,...,0,1,0,0,0,0,0,#차 강릉방향 주행로 주행중 졸음운전으로 차로를 이탈하여 중앙분리대 방현망을 충격하...,"527,820원",중앙분리대 방현망 1조
1,대관령지사,2011-01-01 00:00:00,07:30:00,영동선,215,강릉,본선,본선차로,2/2차로,0.0,...,0,1,0,0,0,0,0,사고차량 인천방향 1차로 주행 중 과속으로 중분대에 설치된 비상회차로 시설물을 차량...,"3,400,000원",중분대 비상 회차로 시설물
2,강릉지사,2011-01-01 00:00:00,06:10:00,동해선,17.8,동해,본선,본선차로,2/2차로,0.0,...,0,2,0,0,0,0,0,사고#1차량 동해방향 1차로 주행중 졸음운전으로 인하여 2차로를 앞서가는 사고#2차...,NaN,없음
3,천안지사,2011-01-01 00:00:00,06:25:00,경부선,342.5,서울,본선,본선차로,1/4차로,0.0,...,0,3,0,0,0,0,0,#2차(소나타)량 1차로 주행중 순간졸음으로 갓길 방음벽을 스치고 1.2차로 구분선...,NaN,없음
4,고성도관,2011-01-01 00:00:00,14:47:00,"중부선,통영-대전선",12.5,통영,본선,본선차로,2/2차로,0.0,...,0,2,0,0,0,0,0,#2차(현대포터) 통영방향 #2차로 운행중 전방 차량 서행으로 제동을 가한것이 미끄...,NaN,없음

In [6]:
file.columns

Index(['지사명', '사고일자', '사고시간', '노선명', '이정', '방향', '발생지점', '구분', '차로',
       '사고전차량통행속도', '사고등급', '사고원인구분', '주 사고원인', '사고직전차량조작', '운전자상태', '교통장애요인',
       '사고시도로환경', '사망', '중상', '경상', '요일', '날씨', '주야구분', '사고유형', '사고차량수',
       '공사보유장비사고', '포장구분', '평면선형', '선형구분', '편경사', '노면상태', '조명시설', '포장상태',
       '작업장구분', '절성토구분', '방책시설(중분대)', '방책시설(갓길)', '원인차차종', '차종구분1', '차종구분2',
       '차종규격', '운전시간', '운전거리(km)', '성별', '원인차운전자연령구분', '피해자_차종', '차종_규격',
       '성별.1', '피해차운전자연령구분', '차량피해(완파)', '차량피해(반파)', '차량피해(경미)', '차량피해((1/3파)',
       '사망자(운전자)', '사망자(보행자)', '사망자(뒷좌석)', '사망안전벨트미착용', '사망에어백작동', '사망에어백미작동',
       '사망에어백없음', '사망유아시트착용', '사망유아시트미착용', '사망유아시트없음', '사고접보방법', '현장도착소요시간',
       '구급차도착소요시간', '인명구조소요시간', '견인차도착소요시간', '구난소요시간', '전면통제시간', '부분통제시간',
       '교통차단시간', '사고처리시간', '도로점유(본선차도)', '도로점유(중분대부근)', '도로점유(중분대승월)',
       '도로점유(갓길)', '도로점유(부가차로)', '도로점유도로이탈(추락)', '도로점유도로이탈(기타)',
       '도로점유진행방향(기타)', '대향차로', '사고후상태(정차)', '사고후상태(전도)', '사고후상태(전복)',
       '차량상태(화재)', '차량상태(잭나이프)', '차량상태(언더라이드)', '사고내용', '시설물피해액', '피해내용'],
      dtype='str')

In [7]:
df = file.replace(r'^\s*$', np.nan, regex=True)

In [8]:
pd.set_option('display.max_rows', None)

df.isna().sum()

지사명                 0
사고일자                0
사고시간                0
노선명                 0
이정                  0
방향                 16
발생지점              563
구분               2493
차로              28673
사고전차량통행속도       15641
사고등급                0
사고원인구분            339
주 사고원인            749
사고직전차량조작         2624
운전자상태            2622
교통장애요인           3599
사고시도로환경          3449
사망                  0
중상                  0
경상                  0
요일                  0
날씨                217
주야구분             1629
사고유형             2088
사고차량수               0
공사보유장비사고         2542
포장구분             2976
평면선형             4457
선형구분            71645
편경사             68104
노면상태                0
조명시설             1137
포장상태            53711
작업장구분               0
절성토구분            8233
방책시설(중분대)        6776
방책시설(갓길)         4579
원인차차종            2183
차종구분1            7539
차종구분2           47406
차종규격            60064
운전시간                0
운전거리(km)            0
성별                437
원인차운전자연령구분       9534
피해자_차종          57997
차종_규격           81081
성별.1            74680
피해차운전자연령구분      59358
차량피해(완파)            0
차량피해(반파)            0
차량피해(경미)            0
차량피해((1/3파)         0
사망자(운전자)            0
사망자(보행자)            0
사망자(뒷좌석)            0
사망안전벨트미착용           0
사망에어백작동             0
사망에어백미작동            0
사망에어백없음             0
사망유아시트착용            0
사망유아시트미착용           0
사망유아시트없음            0
사고접보방법            529
현장도착소요시간            0
구급차도착소요시간           0
인명구조소요시간            0
견인차도착소요시간           0
구난소요시간              0
전면통제시간              0
부분통제시간              0
교통차단시간              0
사고처리시간              0
도로점유(본선차도)          0
도로점유(중분대부근)         0
도로점유(중분대승월)         0
도로점유(갓길)            0
도로점유(부가차로)          0
도로점유도로이탈(추락)        0
도로점유도로이탈(기타)        0
도로점유진행방향(기타)        0
대향차로                0
사고후상태(정차)           0
사고후상태(전도)           0
사고후상태(전복)           0
차량상태(화재)            0
차량상태(잭나이프)          0
차량상태(언더라이드)         0
사고내용                4
시설물피해액          25820
피해내용             1649
dtype: int64

In [9]:
### 총 22개 요소
df['구분'].unique()

<StringArray>
[   '본선차로',       nan,      '내부',      '차로',      '갓길', '고속도로진입부',      '교량',
 '고속도로진출부',     '출구부',      '입구',    '가변차로',     '노즈부',     '진출부', '정류장(BS)',
    '감속차로',     '진입부',    '가속차로',   '평면교차로',  '버스전용차로',   '비상주차대',    '본선TG',
     '입구부']
Length: 22, dtype: str

In [10]:
### 총 9개 요소
df['발생지점'].unique()

<StringArray>
['본선', '램프', 'TG(TCS)', 'TG(하이패스)', '휴게소', '터널', nan, '졸음쉼터', '정류장']
Length: 9, dtype: str

In [11]:
df[df['사고원인구분']=='-'].head()

,지사명,사고일자,사고시간,노선명,이정,방향,발생지점,구분,차로,사고전차량통행속도,...,대향차로,사고후상태(정차),사고후상태(전도),사고후상태(전복),차량상태(화재),차량상태(잭나이프),차량상태(언더라이드),사고내용,시설물피해액,피해내용
65473,제천지사,43049,01:40,중앙선,304.9,춘천,터널,내부,NaN,NaN,...,0,0,0,0,0,0,0,사고차량 춘천방향 음주운전 주행 중 금대2터널내 시설물 충격 후 700m 자가이동...,2952020,터널공동구덮개벽체
65478,부여지사,43049,10:20,서천공주선,25.0,서천,본선,본선차로,1/2차로,109.0,...,0,0,0,0,0,0,0,-사고차량 서천방향 1차로 주행 중 앞서가던 차량에서 튕긴 잡물(각목)로 인하여 앞...,0,-없음
65483,인천지사,43049,16:25,서울외곽순환선,82.0,일산,램프,차로,클로버형,NaN,...,0,0,0,0,0,0,0,사고차량 외곽선 일산방면 계양IC 진출램프(계산동방면) 2차로 주행중 빗길 과속 및...,0,"가드파이프1매, 갓길 방호벽 50cm"
65499,수원지사,43050,14:10,경부선,381.8,서울,본선,본선차로,5/5차로,NaN,...,0,0,0,0,0,0,0,#1차 #2차 서울방향 5차로 각 주행중 #1차 전방주시태만으로 선행하던 #2차 후...,0,"가드레일5매, 지주5본"
65509,수원지사,43051,08:50,경부선,378.5,서울,본선,가속차로,NaN,NaN,...,0,0,0,0,0,0,0,#1차 #2차 5차로 서울방향 각 주행중 #1차 4차로로 급차선 변경중 #2차 좌측...,0,"가드레일2매, 지주3본"

In [12]:
### 사고원인구분 컬럼에서 '-' 값을 nan값으로 변경
df['사고원인구분'] = df['사고원인구분'].astype(str).str.strip().replace('-', np.nan)

In [13]:
df['사고원인구분'].unique()

<StringArray>
['운전자요인', '차량요인', '기타요인', nan]
Length: 4, dtype: str

In [14]:
### 주 사고원인 컬럼에서 '-' 값을 nan값으로 변경
df['주 사고원인'] = df['주 사고원인'].astype(str).str.strip().replace('-', np.nan)

-----
### 주사고원인 데이터 보류

In [15]:
df['주 사고원인'].unique()

<StringArray>
[     '졸음',      '과속',    '주시태만', '안전거리미확보',  '단독차량화재',      '기타',    '도로사정',
 '운전자요인기타',  '제동장치결함',    '노면잡물',    '추월불량',    '무단보행',    '동물침입',   '타이어파손',
    '적재불량',  '차량부품이탈',  '차량결함기타',     '역주행',       nan,   '운전자기타',   '제동 장치',
    '차량기타',     '포트홀',  '운전요인기타']
Length: 24, dtype: str

In [16]:
df[df['주 사고원인'] == '운전자요인기타'].shape

(2007, 91)

In [17]:
df[df['주 사고원인'] == '운전자기타'].shape

(4379, 91)

In [18]:
df[df['주 사고원인'] == '운전요인기타'].shape

(1701, 91)

In [19]:
df[df['주 사고원인'] == '기타'].shape

(1875, 91)

-----

In [20]:
df['사고직전차량조작'].unique()

<StringArray>
['운행차로주행',      nan, '핸들과대조작',  '중앙선침법',   '차로변경',     '기타',   '갓길주행',
 '지정차로위반', '전용차로위반',   '갓길중행',  '중앙선침범']
Length: 11, dtype: str

In [21]:
df[df['사고직전차량조작'] == '기타'].shape

(2945, 91)

In [22]:
df['운전자상태'].unique()

<StringArray>
[    '피로',     '정상',      nan,     '음주',     '기타',     '질병',    '무면허',
  '핸드폰사용',  'DMB시청', '차량기기조작',   '약물중독',   '정신이상']
Length: 12, dtype: str

In [24]:
df['교통장애요인'].unique()

<StringArray>
[                         '장애없음 ',                    '본선정차차량(사고) ',
               '장애없음 본선정차차량(고장) ',                              nan,
                        '교통량 정체 ',                    '갓길정차차량(사고) ',
               '장애없음 갓길정차차량(사고) ',             '교통량 정체 본선정차차량(사고) ',
        '장애없음 교통량 정체 본선정차차량(사고) ',                    '본선정차차량(고장) ',
                      '장애없음 작업장 ',                        '작업으로 정체',
               '장애없음 갓길정차차량(고장) ',               '장애없음 본선정차차량(사고) ',
                   '장애없음 교통량 정체 ',                    '갓길정차차량(고장) ',
                       '돌발상황 정체 ',                   '장애없음 작업으로 정체',
                    '갓길정차차량(기타) ',         '본선정차차량(사고) 갓길정차차량(사고) ',
                           '작업장 ',                    '본선정차차량(기타) ',
               '장애없음 갓길정차차량(기타) ', '돌발상황 정체 본선정차차량(사고) 갓길정차차량(사고) ',
             '작업으로 정체본선정차차량(사고) ',               '장애없음 본선정차차량(기타) ',
        '장애없음 작업으로 정체본선정차차량(사고) ',  '교통량 정체 본선정차차량(사고) 갓길정차차량(사고) ',
            '돌발상황 정체 본선정차차량(사고) ',         '본선정차차량(사고) 갓길정차차량(고장) ',
                           '장애없음',                     '본선정차차량(사고)',
                     '본선정차차량(고장)',                     '갓길정차차량(고장)',
                     '갓길정차차량(사고)',                         '교통량 정체',
                            '작업장',                        '장애없음작업장',
                     '장애없음교통량 정체',                 '장애없음갓길정차차량(고장)',
                        '돌발상황 정체',                 '작업장본선정차차량(기타) ',
                 '장애없음본선정차차량(사고)',           '본선정차차량(사고)본선정차차량(고장)',
                     '본선정차차량(기타)',                          '교통량정체',
                         '작업으로정체',                         '돌발상황정체',
                     '갓길정차차량(기타)']
Length: 49, dtype: str

In [25]:
df['사고시도로환경'].unique()

<StringArray>
[                         '정상 ',                            nan,
                          '기타 ',             '미끄러운 노면(날씨로 인한) ',
             '미끄러운 노면(오염물로 인한)',          '정상 미끄러운 노면(날씨로 인한) ',
                 '시거장애 (기상요인) ',              '정상 시거장애 (기상요인) ',
                   '부적잘한 안전관리 ',                  '시거장애 (시설물) ',
                       '정상 기타 ',                   '시거장애 (수목) ',
                         '물고임 ', '미끄러운 노면(날씨로 인한) 시거장애 (기상요인) ',
          '미끄러운 노면(날씨로 인한) 기타 ',                '정상 시거장애 (역광) ',
       '정상 미끄러운 노면(날씨로 인한) 기타 ',           '정상 시거장애 (기상요인) 기타 ',
               '정상 시거장애 (시설물) ',              '미끄러운 노면(날씨로 인한)',
                           '정상',            '정상미끄러운 노면(날씨로 인한)',
                           '기타',                         '정상기타',
                   '시거장애 (시설물)',                          '물고임',
                  '시거장애 (기상요인)',                    '부적절한 안전관리',
                          '낙하물',                          '포트홀',
                  '교량 신축이음장치파손',                         '토사유출',
                         '소성변형',                   '시거장애(장애요인)',
                     '시거장치(역광)',                  '교량 신축이용장치파손',
                    '시거장애(시설물)',                    '부절적한 안전관리',
                     '시거장애(수목)']
Length: 39, dtype: str

-----
공사보유장비사고 컬럼에서 관련있음과 있음 두 분류 해결 필요

In [26]:
df['공사보유장비사고'].unique()

<StringArray>
['관련없음', '관련있음', '있음', nan]
Length: 4, dtype: str

In [27]:
df['포장구분'].unique()

<StringArray>
['콘크리트', '아스팔트', nan]
Length: 3, dtype: str

In [29]:
df['평면선형'].unique()

<StringArray>
[                '직선  ',         '우커브 1000m 이상',         '좌커브 1000m 이상',
 '좌커브 500m 이상 1000m 미만', '우커브 500m 이상 1000m 미만',          '우커브 500m 미만',
          '좌커브 500m 미만',                   '직선',                    nan,
                  '좌커브',                  '우커브']
Length: 11, dtype: str

In [30]:
df['노면상태'].unique()

<StringArray>
['건조', '습기', '적설', '기타']
Length: 4, dtype: str

In [31]:
df['조명시설'].unique()

<StringArray>
['없음', '해당없음(주간)', '작동', nan, '미작동']
Length: 5, dtype: str

In [32]:
df['작업장구분'].unique()

<StringArray>
['비작업구간',  '확장공사',    '기타', '도로재포장',  '교량보수',  '터널보수', '중분대작업',  '갓길작업',
  '팻칭작업',  '차선도책', '중분대청소',  '갓길청소',    '본선',  '제설작업',  '차선도색']
Length: 15, dtype: str

In [33]:
df['절성토구분'].unique()

<StringArray>
[       '성토고 2M 미만',       '절토부 10M 이상',               '평지',
  '성토고 2M 이상 5M 미만',                nan,       '절토부 10M 미만',
 '성토고 5M 이상 15M 미만',       '성토고 15M 이상']
Length: 8, dtype: str

-----
고정식방호벽(81cm) 2개 , 가드레일 2개, 중분대없음 2개, 녹지대 2개, 이동식방호벽 2개

In [35]:
df['방책시설(중분대)'].unique()

<StringArray>
[   '고정식방호벽(81cm) ',               '기타',    '고정식방호벽(127cm)',
 '녹지대             ',                nan,  '가드레일           ',
    '이동식방호벽       ',   '중분대없음         ',     '고정식방호벽(81cm)',
            '중분대없음',           '이동식방호벽',             '가드레일',
              '녹지대']
Length: 13, dtype: str

----
방책시설(갓길) 컬럼에서 없음 2개, 기타 2개, 가드레일 2개, 콘크리트방호벽 + 콘르리트방호벽, 가드파이프 2개, 가드케이블 2개  정리필요

In [34]:
df['방책시설(갓길)'].unique()

<StringArray>
[  '가드레일       ',       '콘크리트방호벽', '없음           ', '기타           ',
             nan,         '낙석방지책',    '가드케이블     ',          '가드휀스',
    '가드파이프     ',            '없음',            '기타',         '가드파이프',
       '콘르리트방호벽',         '가드케이블',          '가드레일']
Length: 15, dtype: str

-----
원인차차종 컬럼에서 승용 - 승용차 , 화물 - 화물차 , 승합 - 승합차 정리 필요

In [36]:
df['원인차차종'].unique()

<StringArray>
['승용', '트레일러', '화물', '승합', '특수차량', nan, '기타', '승합차', '화물차', '승용차']
Length: 10, dtype: str

In [38]:
df['차종구분1'].unique()

<StringArray>
[     '소형',      '중형',      '대형',       nan,    'SUV형',      '경형',    '일반화물',
      '탑차',    '탱크로리', '대형-전세버스', '대형-고속버스',     '견인형', '대형-좌석버스',     '구급형',
     '이륜차', '도주(미확인)']
Length: 16, dtype: str

-----
운전시간 데이터 삭제

In [39]:
df['운전시간'].unique()

array([           0, 201712271343, 201801030810, 201802010005,
       201802031326, 201803072250, 201803170007, 201803240900,
       201804051600, 201804070202, 201804102347, 201804140202,
       201804171537, 201804192329, 201804251425, 201804251937,
       201805120248, 201805121520, 201805141020, 201805141031,
       201805300004, 201805302230, 201806200120, 201807032237,
       201807182047, 201807230502, 201807231000, 201808300300,
       201809051312, 201809201130, 201809210351, 201809270000,
       201810041920, 201810101205, 201810290800, 201811071403,
       201812201942, 201901202315, 201901271151, 201901310300,
       201901311314, 201902050505, 201902190540, 201902200000,
       201902241959, 201902250000, 201902260210, 201903031445,
       201903061558, 201903081533, 201903162220, 201903232111,
       201904270539, 201905092245, 201905101400, 201905160228,
       201805180411, 201906040333, 201906062151, 201906201548,
       201906261307, 201906280725, 201906291556, 201907050030,
       201907161208, 201907210530, 201907251103, 201907261316,
       201907290330, 201908081647, 201908170748, 201908202348,
       201908281330, 201909020846, 201909070300, 201909081840,
       201909111523, 201909131930, 201909280124, 201910110015,
       201910121248, 201910151131, 201910191410, 201910242321,
       201910261224, 201910272237, 201910280838, 201910310927,
       201910012030, 201911172120, 201911192144, 201911200836,
       201912100153, 201912101315, 201912130348, 201912172150,
       201912231850])

-----
운전거리(km) 삭제 논의 필요

In [41]:
df['운전거리(km)'].unique()

array([  0. ,  17.2,   2. ,  11. , 238. ,  47. ,  24. ,   2.4,  20. ,
        18. ,  25. ,  15. ,   9. ,  61. ,  16. ,  28. ,  65.5, 135. ])

-----
원인차운전자연령구분 데이터 논의 필요

In [46]:
df['원인차운전자연령구분'].unique()

array(['30~40', '20~30', '40~50', '50~60', '60세 이상', nan, '20세 미만',
       '30~39', '40~49', '20~29', '50~59', '기타(잘못입력)', '27.0', '28.0',
       '36.0', '24.0', '0.0', '30.0', '59.0', '55.0', '35.0', '57.0',
       '70.0', '33.0', '51.0', '44.0', '25.0', '60.0', '53.0', '45.0',
       '49.0', '34.0', '61.0', '31.0', '62.0', '43.0', '54.0', '42.0',
       '56.0', '37.0', '47.0', '22.0', '38.0', '68.0', '32.0', '41.0',
       '40.0', '21.0', '26.0', '52.0', '39.0', '63.0', '58.0', '64.0',
       '48.0', '66.0', '50.0', '46.0', '65.0', '29.0', '23.0', '1.0',
       '20.0', '73.0', '69.0', '72.0', '84.0', '77.0', '76.0', '67.0',
       '79.0', '150.0', 0.0, 32.0, 59.0, 26.0, 48.0, 56.0, 29.0, 30.0,
       55.0, 52.0, 45.0, 53.0, 49.0, 35.0, 54.0, 23.0, 19.0, 39.0, 43.0,
       44.0, 38.0, 50.0, 57.0, 40.0, 46.0, 34.0, 31.0, 65.0, 37.0, 28.0,
       24.0, 33.0, 42.0, 70.0, 79.0, 36.0, 58.0, 27.0, 25.0, 66.0, 47.0,
       41.0, 62.0, 64.0, 67.0, 61.0, 74.0, 20.0, 69.0, 22.0, 51.0, 71.0,
       60.0, 78.0, 63.0, 73.0, 68.0, 21.0, 18.0, 16.0, 72.0, 76.0, 540.0,
       84.0, 75.0, 270.0, 420.0, 81.0, 77.0, 510.0, 560.0, 650.0, 5.0,
       630.0, 530.0, 680.0, 350.0, 340.0, 1.0, 83.0, 356.0, 10.0, 280.0,
       330.0, 590.0, 480.0, 92.0, 390.0, 470.0, 82.0, 80.0, 17.0, 220.0,
       2.0, 589.0, 3.0, 9.0, 7.0, 4.0, 8.0, 90.0, 6.0, 91.0, 773.0, 85.0],
      dtype=object)

In [45]:
df[df['원인차운전자연령구분'] == 58.0].shape

(732, 91)

-----
차량피해(완파,반파,경미,1/3파) 데이터 확인 필요

In [48]:
df['차량피해(완파)'].unique()

array([0, 1, 2, 4, 3])

In [49]:
df['차량피해(반파)'].unique()

array([0, 1, 2, 6, 3, 4, 7, 8, 5])

In [50]:
df['사망에어백작동'].unique()

array([0, 1, 2])

In [51]:
df['사고접보방법'].unique()

<StringArray>
[       '고객',       '순찰중',       '콜센터',      '유관기관',       '영업소',      '교통센터',
        '기타',      'CCTV',         nan, '터널사고감지시스템',       '상황실']
Length: 11, dtype: str

In [52]:
df['도로점유(본선차도)'].unique()

array([ 1,  3,  2,  0,  4,  6,  5, 11, 16,  7,  8, 17, 10, 14,  9, 13, 12,
       22, 24, 25, 35, 29, 15, 45, 20, 32])

-----
대향차로 의미 확인 필요

In [53]:
df['대향차로'].unique()

array([0, 1])